# Generates a pretty snake animation using @Platane's awesome snk action
name: 🐍 Generate Snake Contribution GIF

on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '30 23 * * *' # Runs at 23:30 every day.

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generate the snake animation
      - name: Generate Snake GIF and SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-snake.gif
            assets/github-snake.svg
            assets/github-snake-dark.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Commit the changes if there are any
      - name: Commit and Push Changes
        run: |
          git config user.email "martindudi6@gmail.com"
          git config user.name "liss-bot"
          if [ -n "$(git status --porcelain)" ]; then
            git add assets/github-snake.gif assets/github-snake.svg assets/github-snake-dark.svg
            git commit -m "🔄 Updated Snake Contribution Animation"
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Push the changes
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      # Notify on Success or Failure
      - name: Notify via GitHub Issues
        if: failure()
        run: |
          gh issue create --title "Snake GIF Update Failed" --body "The snake GIF update failed in the latest run. Please check the logs."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
